# Generated by Django 4.1.7 on 2023-03-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("systemapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorinheri",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="systemapp.moddegrees",
                verbose_name="Level",
            ),
        ),
    ]
