# Generated by Django 4.1.7 on 2023-03-12 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("systemapp", "0003_alter_employees_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="role",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="user_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User id",
            ),
        ),
    ]
